# CANADIAN NUCLEAR BATTERY SIMULATION STEADY STATE

# Must run with the file param.i:
#   ./cardinal-opt -i param.i steady.i
#   mpiexec -np 4 cardinal-opt -i param.i steady.i --n-threads=4

# =================================================================================================================================
# MESH
# =================================================================================================================================

[Mesh]                                                      # Import mesh generated by running param.i and mesh.i together
    type = FileMesh
    file = mesh_in.e
[]

# =================================================================================================================================
# FUNCTIONS
# =================================================================================================================================

[Functions]
    [axial_power]                                           # Volumetric power density function
        type = ParsedFunction
        expression ='${q0} * sin(pi * (z-${w_vessel}-${w_insulation}-${w_bot_refl}) / ${l_core})'
    []
    [Q_dot_heatpipe_total]                                  # Total Q_dot_out of all heatpipes - sum over tallies
        type = ParsedFunction
        symbol_names = 'hp1 hp2 hp3 hp4 hp5 hp6 hp7 hp8 hp9 hp10 hp11 hp12 hp13 hp14 hp15 hp16 hp17 
                        hp18 hp19 hp20 hp21 hp22 hp23 hp24 hp25 hp26 hp27 hp28 hp29'
        symbol_values = 'hp1_cond_flux_int hp2_cond_flux_int hp3_cond_flux_int hp4_cond_flux_int hp5_cond_flux_int 
                        hp6_cond_flux_int hp7_cond_flux_int hp8_cond_flux_int hp9_cond_flux_int hp10_cond_flux_int hp11_cond_flux_int 
                        hp12_cond_flux_int hp13_cond_flux_int hp14_cond_flux_int hp15_cond_flux_int hp16_cond_flux_int hp17_cond_flux_int 
                        hp18_cond_flux_int hp19_cond_flux_int hp20_cond_flux_int hp21_cond_flux_int hp22_cond_flux_int hp23_cond_flux_int 
                        hp24_cond_flux_int hp25_cond_flux_int hp26_cond_flux_int hp27_cond_flux_int hp28_cond_flux_int hp29_cond_flux_int'
        expression = '-(hp1 + hp2 + hp3 + hp4 + hp5 + hp6 + hp7 + hp8 + hp9 + hp10 + hp11 + hp12 + hp13 + hp14 + hp15 + hp16 + 
                        hp17 + hp18 + hp19 + hp20 + hp21 + hp22 + hp23 + hp24 + hp25 + hp26 + hp27 + hp28 + hp29)'
    []
    [Q_dot_out_total]                                       # Total Q_dot_out of all heatpipes and leakage through wall - sum over tallies
        type = ParsedFunction
        symbol_names = 'Q_dot_heatpipes Q_dot_vessel'
        symbol_values = 'Q_dot_heatpipe_total vessel_flux_int'
        expression = 'Q_dot_heatpipes + Q_dot_vessel'
    []
[]

# =================================================================================================================================
# MATERIALS
# =================================================================================================================================

[Materials]
    [rho_na_l]
        type = ParsedMaterial
        property_name = 'density_na_l'
        constant_names = 'T_c rho_c A B C'
        constant_expressions = '${T_na_c} ${rho_na_c} 275.32 511.58 0.5'
        coupled_variables = 'T'
        expression = 'rho_c + A*(1-T/T_c) + B*pow((1-T/T_c),C)'   
        outputs = exodus    
    []
    [rho_na_v]
        type = ParsedMaterial
        property_name = 'density_na_v'
        upstream_materials = 'h_fg_na gamma_sigma_na rho_na_l'
        material_property_names = 'latient_heat_na gamma_sigma_na density_na_l'
        coupled_variables = 'T'
        expression = '1/((latient_heat_na/1000000)/(gamma_sigma_na*T) + 1/(density_na_l))'
        outputs = exodus    
    []
    [gamma_sigma_na]
        type = ParsedMaterial
        property_name = 'gamma_sigma_na'
        constant_names = 'A B C'
        constant_expressions = '12633.73 -0.4672 11.9463'
        coupled_variables = 'T'
        expression = '(A*pow(T,-2) + B*pow(T,-1)) * exp(C - A*pow(T,-1) + B*log(T))'        
    []
    [h_fg_na]
        type = ParsedMaterial
        property_name = 'latient_heat_na'
        constant_names = 'T_c A B C'
        constant_expressions = '${T_na_c} 393.37 4398.6 0.29302'
        coupled_variables = 'T'
        expression = '(A*(1-T/T_c) + B*pow((1-T/T_c),C))*1e3'
        outputs = exodus
    []
    [mu_na_v]
        type = ParsedMaterial
        property_name = 'dynamic_viscocity_na_v'
        constant_names = 'A B'
        constant_expressions = '208.1 0.155'
        coupled_variables = 'T'
        expression = '(A + B*(T - 1000))*1e-7'
        outputs = exodus
    []
    [k_na_l]
        type = ParsedMaterial
        property_name = 'thermal_conductivity_na_l'
        constant_names = 'A B C D'
        constant_expressions = '124.67 -0.11381 5.5226e-5 -1.1842e-8'
        coupled_variables = 'T'
        expression = 'A + B*T + C*pow(T,2) + D*pow(T,3)'
        outputs = exodus
    []

    [k_steel]
        type = GenericConstantMaterial
        prop_names = 'thermal_conductivity_steel'
        prop_values = 14.3
        outputs = exodus
    []

    [k_vaporcore]
        type = ParsedMaterial
        block = 'vap1 vap2 vap3 vap4 vap5 vap6 vap7 vap8 vap9 vap10 vap11 vap12 vap13 vap14 vap15 vap16 vap17 vap18 vap19 vap20
                 vap21 vap22 vap23 vap24 vap25 vap26 vap27 vap28 vap29'
        constant_names = 'r_v'
        constant_expressions = '${r_vap}'
        property_name = 'thermal_conductivity'
        upstream_materials = 'rho_na_v h_fg_na mu_na_v'
        material_property_names = 'density_na_v latient_heat_na dynamic_viscocity_na_v'
        coupled_variables = 'T'
        expression = '(pow(density_na_v,2) * pow(latient_heat_na,2) * pow(r_v,2)) / (8 * dynamic_viscocity_na_v * T)' 
        outputs = exodus
    []
    [k_wick]
        type = ParsedMaterial
        block = 'wick1 wick2 wick3 wick4 wick5 wick6 wick7 wick8 wick9 wick10 wick11 wick12 wick13 wick14 wick15 wick16 wick17
                 wick18 wick19 wick20 wick21 wick22 wick23 wick24 wick25 wick26 wick27 wick28 wick29 liq1 liq2 liq3 liq4 liq5 
                 liq6 liq7 liq8 liq9 liq10 liq11 liq12 liq13 liq14 liq15 liq16 liq17 liq18 liq19 liq20 liq21 liq22 liq23 liq24
                 liq25 liq26 liq27 liq28 liq29'
        property_name = 'thermal_conductivity'
        constant_names = 'porosity'
        constant_expressions = '${porosity}'
        upstream_materials = 'k_na_l k_steel'
        material_property_names = 'thermal_conductivity_na_l thermal_conductivity_steel'
        expression = 'thermal_conductivity_na_l*((thermal_conductivity_na_l+thermal_conductivity_steel)-(1-porosity)*(thermal_conductivity_na_l-thermal_conductivity_steel))/((thermal_conductivity_na_l+thermal_conductivity_steel)+(1-porosity)*(thermal_conductivity_na_l-thermal_conductivity_steel))'
        outputs = exodus
    []
    [k_graphite]
        type = ParsedMaterial
        block = 'graphite radial_refl top_refl bottom_refl'
        property_name = 'thermal_conductivity'
        constant_names = 'A B C D'
        constant_expressions = '7e-8 -1e-4 -0.0607 159.23'
        coupled_variables = 'T'
        expression = 'A*pow(T,3) + B*pow(T,2) + C*(T) + D'
        outputs = exodus
    []
    [k_compact]
        type = ParsedMaterial
        block = 'compact'
        property_name = 'thermal_conductivity'
        constant_names = 'A B C D'
        constant_expressions = '-3e-9 0.0145 -0.0145 20.234'
        coupled_variables = 'T'
        expression = 'A*pow(T,3) + B*pow(T,2) + C*(T) + D'
    []
    [k_wall]
        type = GenericConstantMaterial
        block = 'wall_e wall_a wall_c wall_hx ctrl_rod vessel'
        prop_names = 'thermal_conductivity'
        prop_values = 14.3
    []
    [k_insulations]
        type = GenericConstantMaterial
        block = 'insulation'
        prop_names = 'thermal_conductivity'
        prop_values = 0.02
    []
    [k_gap]
        type = GenericConstantMaterial
        block = 'gap'
        prop_names = 'thermal_conductivity'
        prop_values = 1.5
    []
[]

# =================================================================================================================================
# PHYSICS
# =================================================================================================================================

[Variables]                                                         # Main variables to solve
    [T] # Temperature
        initial_condition = 823                                     # [k] = 500 deg C
    []
[]

[Kernels]
    # [time_derivative]                                             # rho * cp * dT/dt
    #     type = HeatConductionTimeDerivative
    #     variable = T
    # []    
    [heat_conduction]                                               # div( k * grad( T ) )
        type = HeatConduction
        variable = T 
    []
    [heat_source]                                                   # q_dot_vol
        type = CoupledForce
        variable = T
        v = power_density
        block = 'compact'
    []
[]

[AuxVariables]                                                      # Auxilliary variables to solve
    [power_density]                                                 # power (per unit volume) in the core
        family = MONOMIAL
        order = CONSTANT
    []
[]

[BCs]
    [heat_exchanger]
        type = ConvectiveFluxFunction
        variable = T
        boundary = 'heat_exchanger'
        coefficient = 170                                           # Source: I made it up :)
        T_infinity = ${T_2nd_mean}                                  # From AECL CNB documentation
    []
    [vessel_wall_vertical]
        type = ConvectiveFluxFunction
        variable = T
        boundary = 'external_bound'
        coefficient = 3.83                                          # Assuming free convection to standard air
        T_infinity = 300                                            # Assuming standard ambient temperature
    []
    [vessel_wall_horizontal]
        type = ConvectiveFluxFunction
        variable = T
        boundary = 'bottom'
        coefficient = 2.35                                          # Assuming free convection to standard air
        T_infinity = 300                                            # Assuming standard ambient temperature
    []
    [adiabatic]
        type = NeumannBC
        variable = T
        boundary = 'symmetry top core_top'                          # Assuming Negligible heat loss from vessel top (since it has to free convect thru a lot of helium)
        value = 0
    []
[]

[ICs]
    [power_density]                                                 # Apply power density as initial condition to the fuel via a function
        type = FunctionIC
        variable = power_density
        function = axial_power
        block = 'compact'
    []
[]

# =================================================================================================================================
# SETTINGS
# =================================================================================================================================

[Postprocessors]                                                    # Tallied values during simulation
    [fuel_vol]
        type = VolumePostprocessor
        block = 'compact'
    []
    [T_vap_ave]
        type = ElementAverageValue
        variable = T
        block = 'vap1 vap2 vap3 vap4 vap5 vap6 vap7 vap8 vap9 vap10 vap11 vap12 vap13 vap14 vap15 vap16 vap17 vap18 vap19 vap20
                 vap21 vap22 vap23 vap24 vap25 vap26 vap27 vap28 vap29'
    []
    [T_wick_ave]
        type = ElementAverageValue
        variable = T
        block = 'wick1 wick2 wick3 wick4 wick5 wick6 wick7 wick8 wick9 wick10 wick11 wick12 wick13 wick14 wick15 wick16 wick17
                wick18 wick19 wick20 wick21 wick22 wick23 wick24 wick25 wick26 wick27 wick28 wick29 liq1 liq2 liq3 liq4 liq5 
                liq6 liq7 liq8 liq9 liq10 liq11 liq12 liq13 liq14 liq15 liq16 liq17 liq18 liq19 liq20 liq21 liq22 liq23 liq24
                liq25 liq26 liq27 liq28 liq29'
    []
    [T_hp_ave]
        execute_on = TIMESTEP_BEGIN
        type = ElementAverageValue
        variable = T
        block = 'vap1 vap2 vap3 vap4 vap5 vap6 vap7 vap8 vap9 vap10 vap11 vap12 vap13 vap14 vap15 vap16 vap17 vap18 vap19 vap20
                 vap21 vap22 vap23 vap24 vap25 vap26 vap27 vap28 vap29 wick1 wick2 wick3 wick4 wick5 wick6 wick7 wick8 wick9 wick10 wick11 wick12 wick13 wick14 wick15 wick16 wick17
                 wick18 wick19 wick20 wick21 wick22 wick23 wick24 wick25 wick26 wick27 wick28 wick29 liq1 liq2 liq3 liq4 liq5 
                 liq6 liq7 liq8 liq9 liq10 liq11 liq12 liq13 liq14 liq15 liq16 liq17 liq18 liq19 liq20 liq21 liq22 liq23 liq24
                 liq25 liq26 liq27 liq28 liq29'
    []
    [T_mod_ave]
        type = ElementAverageValue
        variable = T
        block = 'graphite'
    []
    [T_mod_max]
        type = ElementExtremeValue
        variable = T
        block = 'graphite'
    []
    [T_fuel_ave]
        type = ElementAverageValue
        variable = T
        block = 'compact'
    []
    [T_fuel_max]
        type = ElementExtremeValue
        variable = T
        block = 'compact'
    []
    [T_vessel_wall]
        type = SideAverageValue
        variable = T
        boundary = 'bottom external_bound'
    []
    [k_graphite]
        type = ElementAverageMaterialProperty
        mat_prop = thermal_conductivity
        block = 'graphite'
    []
    [k_compact]
        type = ElementAverageMaterialProperty
        mat_prop = thermal_conductivity
        block = 'compact'
    [] 
    [k_vapor]
        type = ElementAverageMaterialProperty
        mat_prop = thermal_conductivity
        block = 'vap1 vap2 vap3 vap4 vap5 vap6 vap7 vap8 vap9 vap10 vap11 vap12 vap13 vap14 vap15 vap16 vap17 vap18 vap19 vap20
                 vap21 vap22 vap23 vap24 vap25 vap26 vap27 vap28 vap29'
    []
    [k_wick]
        type = ElementAverageMaterialProperty
        mat_prop = thermal_conductivity
        block = 'wick1 wick2 wick3 wick4 wick5 wick6 wick7 wick8 wick9 wick10 wick11 wick12 wick13 wick14 wick15 wick16 wick17
                wick18 wick19 wick20 wick21 wick22 wick23 wick24 wick25 wick26 wick27 wick28 wick29 liq1 liq2 liq3 liq4 liq5 
                liq6 liq7 liq8 liq9 liq10 liq11 liq12 liq13 liq14 liq15 liq16 liq17 liq18 liq19 liq20 liq21 liq22 liq23 liq24
                liq25 liq26 liq27 liq28 liq29'
    []
    # ElementIntegralVariablePostprocessor Returns mass = volume_integral(density dV)
    [power]
        type = ElementIntegralVariablePostprocessor
        variable = power_density
        block = 'compact'
    []
    [Q_dot_heatpipes_tot]
        type = FunctionValuePostprocessor
        function = Q_dot_heatpipe_total
    []
    [Q_dot_out_tot]
        type = FunctionValuePostprocessor
        function = Q_dot_out_total
    []       
    # SideDiffusiveFluxIntegral Returns Q_dot = surf_integral(k*dT/dx dA) (W)
    # SideDiffusiveFluxAverage Returns q_dot = surf_integral(k*dT/dx dA) / surf_integral(dA) (W/m^2)
    [vessel_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'bottom external_bound'
        diffusivity = 14.3
    []
    [hp1_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_1'
        diffusivity = 14.3
    []
    [hp1_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_1'
        diffusivity = 14.3
    []
    [hp1_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_1'
        diffusivity = 14.3
    []
    [hp2_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_2'
        diffusivity = 14.3
    []
    [hp2_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_2'
        diffusivity = 14.3
    []
    [hp2_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_2'
        diffusivity = 14.3
    []
    [hp3_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_3'
        diffusivity = 14.3
    []
    [hp3_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_3'
        diffusivity = 14.3
    []
    [hp3_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_3'
        diffusivity = 14.3
    []
    [hp4_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_4'
        diffusivity = 14.3
    []
    [hp4_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_4'
        diffusivity = 14.3
    []
    [hp4_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_4'
        diffusivity = 14.3
    []
    [hp5_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_5'
        diffusivity = 14.3
    []
    [hp5_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_5'
        diffusivity = 14.3
    []
    [hp5_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_5'
        diffusivity = 14.3
    []
    [hp6_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_6'
        diffusivity = 14.3
    []
    [hp6_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_6'
        diffusivity = 14.3
    []
    [hp6_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_6'
        diffusivity = 14.3
    []
    [hp7_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_7'
        diffusivity = 14.3
    []
    [hp7_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_7'
        diffusivity = 14.3
    []
    [hp7_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_7'
        diffusivity = 14.3
    []
    [hp8_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_8'
        diffusivity = 14.3
    []
    [hp8_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_8'
        diffusivity = 14.3
    []
    [hp8_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_8'
        diffusivity = 14.3
    []
    [hp9_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_9'
        diffusivity = 14.3
    []
    [hp9_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_9'
        diffusivity = 14.3
    []
    [hp9_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_9'
        diffusivity = 14.3
    []
    [hp10_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_10'
        diffusivity = 14.3
    []
    [hp10_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_10'
        diffusivity = 14.3
    []
    [hp10_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_10'
        diffusivity = 14.3
    []

    [hp11_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_11'
        diffusivity = 14.3
    []
    [hp11_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_11'
        diffusivity = 14.3
    []
    [hp11_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_11'
        diffusivity = 14.3
    []
    [hp12_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_12'
        diffusivity = 14.3
    []
    [hp12_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_12'
        diffusivity = 14.3
    []
    [hp12_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_12'
        diffusivity = 14.3
    []
    [hp13_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_13'
        diffusivity = 14.3
    []
    [hp13_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_13'
        diffusivity = 14.3
    []
    [hp13_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_13'
        diffusivity = 14.3
    []
    [hp14_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_14'
        diffusivity = 14.3
    []
    [hp14_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_14'
        diffusivity = 14.3
    []
    [hp14_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_14'
        diffusivity = 14.3
    []
    [hp15_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_15'
        diffusivity = 14.3
    []
    [hp15_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_15'
        diffusivity = 14.3
    []
    [hp15_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_15'
        diffusivity = 14.3
    []
    [hp16_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_16'
        diffusivity = 14.3
    []
    [hp16_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_16'
        diffusivity = 14.3
    []
    [hp16_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_16'
        diffusivity = 14.3
    []
    [hp17_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_17'
        diffusivity = 14.3
    []
    [hp17_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_17'
        diffusivity = 14.3
    []
    [hp17_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_17'
        diffusivity = 14.3
    []
    [hp18_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_18'
        diffusivity = 14.3
    []
    [hp18_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_18'
        diffusivity = 14.3
    []
    [hp18_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_18'
        diffusivity = 14.3
    []
    [hp19_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_19'
        diffusivity = 14.3
    []
    [hp19_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_19'
        diffusivity = 14.3
    []
    [hp19_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_19'
        diffusivity = 14.3
    []
    [hp20_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_20'
        diffusivity = 14.3
    []
    [hp20_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_20'
        diffusivity = 14.3
    []
    [hp20_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_20'
        diffusivity = 14.3
    []
    [hp21_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_21'
        diffusivity = 14.3
    []
    [hp21_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_21'
        diffusivity = 14.3
    []
    [hp21_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_21'
        diffusivity = 14.3
    []
    [hp22_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_22'
        diffusivity = 14.3
    []
    [hp22_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_22'
        diffusivity = 14.3
    []
    [hp22_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_22'
        diffusivity = 14.3
    []
    [hp23_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_23'
        diffusivity = 14.3
    []
    [hp23_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_23'
        diffusivity = 14.3
    []
    [hp23_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_23'
        diffusivity = 14.3
    []
    [hp24_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_24'
        diffusivity = 14.3
    []
    [hp24_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_24'
        diffusivity = 14.3
    []
    [hp24_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_24'
        diffusivity = 14.3
    []
    [hp25_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_25'
        diffusivity = 14.3
    []
    [hp25_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_25'
        diffusivity = 14.3
    []
    [hp25_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_25'
        diffusivity = 14.3
    []
    [hp26_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_26'
        diffusivity = 14.3
    []
    [hp26_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_26'
        diffusivity = 14.3
    []
    [hp26_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_26'
        diffusivity = 14.3
    []
    [hp27_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_27'
        diffusivity = 14.3
    []
    [hp27_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_27'
        diffusivity = 14.3
    []
    [hp27_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_27'
        diffusivity = 14.3
    []
    [hp28_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_28'
        diffusivity = 14.3
    []
    [hp28_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_28'
        diffusivity = 14.3
    []
    [hp28_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_28'
        diffusivity = 14.3
    []
    [hp29_evap_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_wick_evap_29'
        diffusivity = 14.3
    []
    [hp29_adiab_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_adiab_29'
        diffusivity = 14.3
    []
    [hp29_cond_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_liq_cond_29'
        diffusivity = 14.3
    []
    [hp1_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_1'
        diffusivity = 14.3
    []
    [hp2_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_2'
        diffusivity = 14.3
    []
    [hp3_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_3'
        diffusivity = 14.3
    []
    [hp4_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_4'
        diffusivity = 14.3
    []
    [hp5_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_5'
        diffusivity = 14.3
    []
    [hp6_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_6'
        diffusivity = 14.3
    []
    [hp7_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_7'
        diffusivity = 14.3
    []
    [hp8_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_8'
        diffusivity = 14.3
    []
    [hp9_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_9'
        diffusivity = 14.3
    []
    [hp10_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_10'
        diffusivity = 14.3
    []
    [hp11_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_11'
        diffusivity = 14.3
    []
    [hp12_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_12'
        diffusivity = 14.3
    []
    [hp13_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_13'
        diffusivity = 14.3
    []
    [hp14_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_14'
        diffusivity = 14.3
    []
    [hp15_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_15'
        diffusivity = 14.3
    []
    [hp16_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_16'
        diffusivity = 14.3
    []
    [hp17_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_17'
        diffusivity = 14.3
    []
    [hp18_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_18'
        diffusivity = 14.3
    []
    [hp19_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_19'
        diffusivity = 14.3
    []
    [hp20_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_20'
        diffusivity = 14.3
    []
    [hp21_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_21'
        diffusivity = 14.3
    []
    [hp22_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_22'
        diffusivity = 14.3
    []
    [hp23_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_23'
        diffusivity = 14.3
    []
    [hp24_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_24'
        diffusivity = 14.3
    []
    [hp25_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_25'
        diffusivity = 14.3
    []
    [hp26_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_26'
        diffusivity = 14.3
    []
    [hp27_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_27'
        diffusivity = 14.3
    []
    [hp28_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_28'
        diffusivity = 14.3
    []
    [hp29_bot_flux_int]
        type = SideDiffusiveFluxIntegral
        variable = T
        boundary = 'wall_vap_bot_29'
        diffusivity = 14.3
    []
    [q0]
        type = ConstantPostprocessor
        value = ${q0}
    []
    [num_DOF]
        type = NumDOFs
    []
    [num_variables]
        type = NumVars
    []
    [rad_mesh_density]
        type = ConstantPostprocessor
        value = ${rad_mesh_density}
    []
    [az_mesh_density]
        type = ConstantPostprocessor
        value = ${az_mesh_density}
    []
    [z_mesh_density]
        type = ConstantPostprocessor
        value = ${z_mesh_density}
    []
    [concentric_mesh_density]
        type = ConstantPostprocessor
        value = ${concentric_mesh_density}
    []
    [gap_mesh_density]
        type = ConstantPostprocessor
        value = ${gap_mesh_density}
    []
    [heatpipe_mesh_density]
        type = ConstantPostprocessor
        value = ${heatpipe_mesh_density}
    []
    [misc_mesh_density]
        type = ConstantPostprocessor
        value = ${misc_mesh_density}
    []
[]

[Executioner]
    type = Transient
    dt = 0.1
    # num_steps = 10

    steady_state_detection = true
    steady_state_tolerance = 1e-04

    nl_abs_tol = 1e-5
    nl_rel_tol = 1e-16
    automatic_scaling = true

    scheme = 'implicit-euler'
    petsc_options_value = 'hypre boomeramg'
    petsc_options_iname = '-pc_type -pc_hypre_type'
    line_search = 'none'

    print_linear_residuals = true
    abort_on_solve_fail = true
[]

[Outputs]
    exodus = true
    csv = true
[]

[Debug]
    show_var_residual_norms = true
[]